FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
  nginx \
  git \
  curl \
  libpng-dev \
  libonig-dev \
  libxml2-dev \
  zip \
  unzip \
  supervisor \
  librabbitmq-dev \
  libpq-dev \
  libzip-dev

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip pdo_pgsql

RUN pecl install amqp redis \
  && docker-php-ext-enable amqp redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY .docker/nginx/dev.conf /etc/nginx/conf.d/default.conf
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
  && ln -sf /dev/stderr /var/log/nginx/error.log

RUN sed -i 's/^listen =.*/listen = 9000/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.max_children = 5/pm.max_children = 20/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.start_servers = 2/pm.start_servers = 5/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.min_spare_servers = 1/pm.min_spare_servers = 5/' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/pm.max_spare_servers = 3/pm.max_spare_servers = 10/' /usr/local/etc/php-fpm.d/www.conf

WORKDIR /var/www

COPY composer.json composer.lock ./
RUN composer install

COPY . .

RUN composer dump-autoload --optimize

COPY .docker/php/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN mkdir -p /var/log/nginx /var/log/php \
  && chown -R www-data:www-data /var/log/nginx /var/log/php \
  && chmod -R 755 /var/log/nginx /var/log/php

EXPOSE 80

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"] 
